---
- name: configure Magento2 to Vagrant CentOS7
  hosts: all
  max_fail_percentage: 0
  sudo: yes
  roles:
    - centos7-init
    - lamp56
    - change-timezone-ja
    - install-dev-tools
    - magento2
    - magento2-site-configuration
    # - magento2-import-sample
