---
- name: yum install epel rpm
  yum: name={{ item }} state=present
  with_items:
    - epel-release

- name: ius rpm for php7
  yum: state=present name=http://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm

- name: get mysql57 rpm
  get_url:
    url: http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
    dest: /home/vagrant/mysql57-community-release-el7-7.noarch.rpm

- name: install mysql57 rpm
  yum:
    name: /home/vagrant/mysql57-community-release-el7-7.noarch.rpm
    state: present

- name: yum update all to replace default mariadb packages automatically
  yum: name=* state=latest

- name: install LAMP7057 basic packages
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - httpd-devel
    - mod_php70u
    - php70u-devel
    - php70u-pdo
    - php70u-mysqlnd
    - mysql-community-client
    - mysql-community-server

- name: Start httpd
  service:
    name: httpd
    state: started
    enabled: yes

- name: Start mysqld
  service:
    name: mysqld
    state: started
    enabled: yes
