---
- name: Install webtatic php56/el7 rpm
  yum: state=present name=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm

- name: add MariaDB.repo
  copy: src=MariaDB.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

- name: yum install LAMP56 basic packages
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - httpd-devel
    - php56w
    - php56w-devel
    - php56w-mysql
    - MariaDB-server
    - MariaDB-client
    - MariaDB-devel

- name: set utf8 to my.cnf
  lineinfile: dest=/etc/my.cnf.d/server.cnf regexp="^\[mysqld\]" insertafter="^\[mysqld\]" line="[mysqld]\ncharacter-set-server = utf8"

- name: Start httpd
  service:
    name: httpd
    state: started
    enabled: yes

- name: Start mariadb
  service:
    name: mysql
    state: started
    enabled: yes
