---

# Install requirements

- name: yum install php requirement packages for Magento2
  yum: name={{ item }} state=present
  with_items:
    - php56w
    - php56w-opcache
    - php56w-xml
    - php56w-mcrypt
    - php56w-gd
    - php56w-devel
    - php56w-mysql
    - php56w-intl
    - php56w-mbstring

- name: yum install others requirement packages for Magento2 installation
  yum: name={{ item }} state=present
  with_items:
    - curl
    - ImageMagick

- name: yum install optional packages for Magento2
  yum: name={{ item }} state=present
  with_items:
    - php56w-pecl-xdebug
    - php-phpunit-PHPUnit

- name: Set always_populate_raw_post_data disable on php.ini(php56)
  lineinfile:
    dest: /etc/php.ini
    backrefs: yes
    regexp: '^;always_populate_raw_post_data'
    line: 'always_populate_raw_post_data = -1'

- name: Set max memory 768MB
  lineinfile:
    dest: /etc/php.ini
    backrefs: yes
    regexp: '^memory_limit'
    line: 'memory_limit = 768M'

- name: Change httpd.conf
  copy: src=httpd.conf.2.4.6 dest=/etc/httpd/conf/httpd.conf owner=root group=root mode=0644

- name: Install composer globally
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Set github token for composer installation
  shell: composer config -g github-oauth.github.com {{ github_token }}
  sudo: no

# Install magento2 app

- name: chown /var/www/html
  file: path=/var/www/html state=directory owner=vagrant group=vagrant

- name: Install magento2
  shell: composer create-project magento/project-community-edition --stability="beta" magento2
  args:
    chdir: /var/www/html
  sudo: no

- name: add user vagrant to apache group
  user: name=vagrant append=yes groups="apache"

- name: add user apache to vagrant group
  user: name=apache append=yes groups="vagrant"

- name: chown /var/www/html
  file: path=/var/www/html state=directory recurse=yes owner=apache group=apache

- name: Set permission to app directory
  shell: find /var/www/html/ -type d -exec chmod 770 {} \;

- name: Set Permission to app files
  shell: find /var/www/html/ -type f -exec chmod 660 {} \;

- name: Add execute Permission to app/bin directory
  shell: chmod +x /var/www/html/magento2/bin/magento

# set PATH magento-cli

- name: add magento-cli PATH to .bash_profile
  lineinfile: dest=/home/vagrant/.bash_profile line="export PATH=$PATH:/var/www/html/magento2/bin"

# init db

- name: Install mysql-python package for ansible configuration
  yum: name=MySQL-python state=present

- name: ensure anonymous users are not in the database
  mysql_user: name='' state=absent

- name: remove the test database
  mysql_db: name=test state=absent

# create magento2 db

- name: Create Magento database
  mysql_db: name={{ db_name }} collation=utf8_general_ci encoding=utf8 state=present

- name: Create Magento database user
  mysql_user: name={{ db_user }} password={{ db_password }} priv={{ db_name }}.*:ALL host='localhost' state=present

- name: update mysql root password for all root accounts
  mysql_user: name=root password=password state=present

# Configure setting to httpd

- name: Restart httpd
  service: name=httpd state=restarted

- name: Wait for httpd restarted
  wait_for: port=80 delay=30
